on: [push, pull_request]
name: Test
jobs:
  terraform-format:
    runs-on: ubuntu-18.04
    steps:
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 1.1.5
      - uses: actions/checkout@v2
        name: Checkout source code
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: module
  terraform-validate:
    runs-on: ubuntu-18.04
    steps:
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 1.1.5
      - uses: actions/checkout@v2
        name: Checkout source code
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: module
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: module
  terraform-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 1.1.5
      - uses: actions/checkout@v2
        name: Checkout source code
      - name: tflint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.github_token }}
          flags: "-c .tflint.hcl"
          fail_on_error: "true"
          reporter: github-check
          filter_mode: "nofilter"
  terratest:
    runs-on: ubuntu-18.04
    services:
      ## Localstack
      ## All the containers in a job are connected to the same Docker network. This means you can access other containers using their network alias (we assign the network alias based on the service name)
      localhost:
        image: localstack/localstack:latest
        env:
          SERVICES: sts,s3
          DEFAULT_REGION: eu-west-1
        ports:
          - 4566:4566
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Setup Dependencies
        working-directory: test/terratest
        run:  go get -v -t -d && go mod tidy
      - name: Test
        working-directory: test/terratest
        run: go test -v
        env:
          AWS_ACCESS_KEY_ID: "null"
          AWS_SECRET_ACCESS_KEY: "null"
